Update issue templates
PoliticalComputerScience/PCS-Website pull request #1
Opened 2024-06-19 18:56 UTC by VivianWilde

Added Bug Report, Feature Request, and Task templates

2024-06-20 02:50 UTC, na933950 commented on .github/ISSUE_TEMPLATE/task.md
> +name: Task
Capitalize please.

2024-06-20 02:51 UTC, na933950 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +name: Bug report
Capitalize

2024-06-20 02:52 UTC, na933950 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +name: Feature request
Capitalize

2024-06-20 02:55 UTC, na933950 commented on .github/ISSUE_TEMPLATE/task.md
Is this meant to be a ticket of sorts? I.e someone makes a task assignment when they find a new task to be completed? If so, we can use the [Project Manager](https://github.com/orgs/PoliticalComputerScience/projects/1) feature and then you can hit "Create an issue" and all three of these should be taken care of. If there markdown files are just here as templates for the issues there than this works.

2024-06-20 02:55 UTC, na933950 requested changes
See comments

2024-06-21 00:05 UTC, VivianWilde commented on .github/ISSUE_TEMPLATE/task.md
These are meant to be templates, so when you create an issue you have an option to specify if it's one of these categories. "Task" specifically is meant to be more a general class of "things to do" that don't come under features or bugs. For instance "refactor/document X", etc.

2024-06-21 02:41 UTC, na933950 approved these changes

2024-06-21 02:41 UTC, na933950 approved these changes

2024-06-21 04:23 UTC, merged