Create Footer component
PoliticalComputerScience/PCS-Website pull request #38
Opened 2024-08-11 04:38 UTC by VivianWilde

# Issue Number

Closes #19 

# Type of Change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# Details

Created a footer component, and added it to the homepage.

# Screenshots
![2024-08-10_21-36](https://github.com/user-attachments/assets/d8918c94-7501-461e-944c-65a38e24c327)

![2024-08-10_21-17](https://github.com/user-attachments/assets/6f11ff82-a253-4f90-a68f-ddace4f8f2cf)

# How Has This Been Tested?

Visually, via Firefox. Tested on both mobile and desktop viewports

# Checklist

- [X] Code is formatted in line with the style guidelines
- [ ] Every function has a JSDoc that is up-to-date with my changes
- [ ] I have added tests for the new behaviour, and they pass

2024-08-11 19:01 UTC, na933950 requested changes
Codewise, looks good but the footer doesn't match the one from the Figma. Can worry about links to the "Projects", "External Events", etc. pages later because I'm working on that routing, but the background should the mesh gradient and there are other small changes.

![image](https://github.com/user-attachments/assets/6de31396-6af1-4195-bc26-8f73cb558be9)
![image](https://github.com/user-attachments/assets/3e32c03a-9a3d-4160-aadb-40a3f8bde2cb)

2024-08-12 03:08 UTC, VivianWilde commented
![2024-08-11_20-04_1](https://github.com/user-attachments/assets/aac1f1db-12d2-43ea-a9ae-6d4a19d363f6)
![2024-08-11_20-04](https://github.com/user-attachments/assets/7f9b35e7-8a8b-4e2e-ace7-ff63000124ad)
Made the changes! Here's how it looks now, I think I got everything.

2024-08-12 05:21 UTC, na933950 commented
What are the faint images in the background?

2024-08-12 05:21 UTC, na933950 approved these changes

2024-08-23 22:55 UTC, merged